# Generated by Django 2.2.6 on 2019-11-19 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Κατάσταση')),
                ('title', models.CharField(max_length=240, unique=True, verbose_name='Τίτλος')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αξία Καλαθιού')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Ποσότητα')),
                ('category', models.CharField(choices=[('c', 'Μηνες'), ('a', 'Μέρες'), ('b', 'Εβδομαδες')], max_length=1, verbose_name='Κατηγορία')),
                ('category_type', models.CharField(choices=[('a', 'Καφέδες'), ('b', 'Φαγητό')], max_length=1, verbose_name='Ειδος Συνδρομης')),
                ('ordering', models.PositiveIntegerField(default=1, verbose_name='Ταξινόμηση')),
                ('uses', models.IntegerField(default=1, verbose_name='Χρησεις')),
                ('products', models.ManyToManyField(blank=True, null=True, to='catalogue.Product')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Κατασταση')),
                ('is_paid', models.BooleanField(default=False)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('uses', models.IntegerField(default=1, verbose_name='Υπόλοιπο Χρησεων')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.Subscribe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_subscribes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
