# Generated by Django 2.2 on 2019-10-22 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=240, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('counter', models.PositiveIntegerField(default=3)),
                ('category', models.CharField(choices=[('a', 'Μέρες'), ('b', 'Εβδομαδες'), ('c', 'Μηνες')], max_length=1)),
                ('ordering', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_start', models.DateField(blank=True)),
                ('date_end', models.DateField(blank=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('uses', models.IntegerField(default=0)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.Subscribe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
