# Generated by Django 2.2 on 2019-10-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('b', 'Εβδομαδες'), ('c', 'Μηνες'), ('a', 'Μέρες')], max_length=1, verbose_name='Κατηγορία'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Ποσότητα'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='ordering',
            field=models.PositiveIntegerField(default=1, verbose_name='Ταξινόμηση'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='title',
            field=models.CharField(max_length=240, unique=True, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αξία Καλαθιού'),
        ),
        migrations.AlterField(
            model_name='usersubscribe',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscribe',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscribe',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
