# Generated by Django 2.2 on 2019-10-24 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20191023_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('a', 'Μέρες'), ('b', 'Εβδομαδες'), ('c', 'Μηνες')], max_length=1, verbose_name='Κατηγορία'),
        ),
        migrations.AlterField(
            model_name='usersubscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_subscribes', to=settings.AUTH_USER_MODEL),
        ),
    ]
