# Generated by Django 2.2.6 on 2019-10-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20191024_1356'),
        ('subscribe', '0003_auto_20191024_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.Product'),
        ),
        migrations.AlterField(
            model_name='usersubscribe',
            name='uses',
            field=models.IntegerField(default=1),
        ),
    ]
