# Generated by Django 2.2.6 on 2019-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_auto_20191026_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='uses',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('b', 'Εβδομαδες'), ('c', 'Μηνες'), ('a', 'Μέρες')], max_length=1, verbose_name='Κατηγορία'),
        ),
    ]
