# Generated by Django 2.2.6 on 2020-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_auto_20200116_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('a', 'Μέρες'), ('b', 'Εβδομαδες'), ('c', 'Μηνες')], max_length=1, verbose_name='Κατηγορία'),
        ),
    ]
