# Generated by Django 2.2.6 on 2019-10-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_auto_20191027_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('c', 'Μηνες'), ('a', 'Μέρες'), ('b', 'Εβδομαδες')], max_length=1, verbose_name='Κατηγορία'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='uses',
            field=models.IntegerField(default=1, verbose_name='Χρησεις'),
        ),
    ]
