# Generated by Django 2.2 on 2020-01-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0009_auto_20200118_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('a', 'Μέρες'), ('b', 'Εβδομαδες'), ('c', 'Μηνες')], max_length=1, verbose_name='Κατηγορία'),
        ),
    ]
