# Generated by Django 2.2 on 2020-01-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0010_auto_20200118_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('a', 'Μέρες'), ('c', 'Μηνες'), ('b', 'Εβδομαδες')], max_length=1, verbose_name='Κατηγορία'),
        ),
    ]
