# Generated by Django 2.2 on 2020-05-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0014_auto_20200517_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('b', 'Εβδομαδες'), ('a', 'Μέρες'), ('c', 'Μηνες')], max_length=1, verbose_name='Κατηγορία'),
        ),
    ]
