# Generated by Django 2.2 on 2020-05-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0016_auto_20200517_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('c', 'Μηνες'), ('b', 'Εβδομαδες'), ('a', 'Μέρες')], max_length=1, verbose_name='Κατηγορία'),
        ),
    ]
