# Generated by Django 2.2 on 2020-05-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0017_auto_20200517_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('b', 'Εβδομαδες'), ('c', 'Μηνες'), ('a', 'Μέρες')], max_length=1, verbose_name='Κατηγορία'),
        ),
    ]
