# Generated by Django 2.2 on 2019-11-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0019_auto_20191110_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('c', 'Μηνες'), ('a', 'Μέρες'), ('b', 'Εβδομαδες')], max_length=1, verbose_name='Κατηγορία'),
        ),
    ]
