# Generated by Django 2.2.6 on 2019-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0021_auto_20191111_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='category_type',
            field=models.CharField(choices=[('a', 'Καφέδες'), ('b', 'Φαγητό')], default='a', max_length=1, verbose_name='Ειδος Συνδρομης'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='category',
            field=models.CharField(choices=[('b', 'Εβδομαδες'), ('a', 'Μέρες'), ('c', 'Μηνες')], max_length=1, verbose_name='Κατηγορία'),
        ),
    ]
