# Generated by Django 2.2.6 on 2019-11-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0022_auto_20191111_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscribe',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Κατασταση'),
        ),
        migrations.AlterField(
            model_name='usersubscribe',
            name='uses',
            field=models.IntegerField(default=1, verbose_name='Υπόλοιπο Χρησεων'),
        ),
    ]
