# Generated by Django 2.2.6 on 2020-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
