# Generated by Django 2.2.6 on 2019-11-22 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0002_auto_20191121_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 11, 22), verbose_name='Ημερομηνία'),
        ),
    ]
