# Generated by Django 2.2 on 2019-10-22 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0003_auto_20191004_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order_related',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 10, 22), verbose_name='Ημερομηνία'),
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
