# Generated by Django 2.2 on 2019-10-23 12:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0004_auto_20191022_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 10, 23), verbose_name='Ημερομηνία'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='Postal')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Phone')),
                ('cellphone', models.CharField(blank=True, max_length=10, verbose_name='Cell Phone')),
                ('order_related', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Order')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='Postal')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Phone')),
                ('cellphone', models.CharField(blank=True, max_length=10, verbose_name='Cell Phone')),
                ('need_invoice', models.BooleanField(default=False)),
                ('is_retail', models.BooleanField(default=True)),
                ('is_eshop', models.BooleanField(default=True)),
                ('vat', models.CharField(blank=True, max_length=9, verbose_name='ΑΦΜ')),
                ('vat_city', models.CharField(blank=True, max_length=100, null=True)),
                ('company_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('order_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Order')),
            ],
        ),
    ]
