# Generated by Django 2.2.6 on 2020-01-16 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0004_auto_20191124_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2020, 1, 16), verbose_name='Ημερομηνία'),
        ),
    ]
