# Generated by Django 2.2 on 2019-10-24 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0005_auto_20191023_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 10, 24), verbose_name='Ημερομηνία'),
        ),
    ]
