# Generated by Django 2.2.6 on 2020-01-17 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0005_auto_20200116_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2020, 1, 17), verbose_name='Ημερομηνία'),
        ),
    ]
