# Generated by Django 2.2 on 2020-01-18 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0006_auto_20200117_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2020, 1, 18), verbose_name='Ημερομηνία'),
        ),
    ]
