# Generated by Django 2.2.6 on 2019-10-27 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0007_auto_20191026_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 10, 27), verbose_name='Ημερομηνία'),
        ),
    ]
