# Generated by Django 2.2 on 2019-10-29 06:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_subscribe_value'),
        ('catalogue', '0005_auto_20191024_1356'),
        ('subscribe', '0008_auto_20191029_0813'),
        ('point_of_sale', '0008_auto_20191027_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscribe_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='subscribe_discount_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 10, 29), verbose_name='Ημερομηνία'),
        ),
        migrations.CreateModel(
            name='OrderSubscribeDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('uses', models.IntegerField(default=0)),
                ('order_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Order')),
                ('subscription', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.UserSubscribe')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('cart_gift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.CartItemGifts')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.OrderItem')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Product')),
            ],
        ),
    ]
