# Generated by Django 2.2.6 on 2019-10-31 04:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0009_auto_20191029_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 10, 31), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='ordergift',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.OrderItem'),
        ),
    ]
