# Generated by Django 2.2.6 on 2019-10-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20191031_0653'),
        ('point_of_sale', '0010_auto_20191031_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemattribute',
            name='attribute',
        ),
        migrations.AddField(
            model_name='orderitemattribute',
            name='attribute',
            field=models.ManyToManyField(null=True, to='catalogue.Attribute'),
        ),
    ]
