# Generated by Django 2.2 on 2020-09-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0011_auto_20200518_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2020, 9, 10), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνια Δημιουργιας'),
        ),
    ]
