# Generated by Django 2.2.4 on 2021-06-06 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0012_auto_20200910_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2021, 6, 6), verbose_name='Ημερομηνία'),
        ),
    ]
