# Generated by Django 2.2.6 on 2019-11-03 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0012_auto_20191102_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 11, 3), verbose_name='Ημερομηνία'),
        ),
    ]
