# Generated by Django 2.2.4 on 2021-06-09 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0013_auto_20210606_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2021, 6, 9), verbose_name='Ημερομηνία'),
        ),
    ]
