# Generated by Django 2.2.6 on 2019-11-10 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0014_auto_20191108_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 11, 10), verbose_name='Ημερομηνία'),
        ),
    ]
