# Generated by Django 2.2 on 2019-11-11 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20191110_1518'),
        ('subscribe', '0021_auto_20191111_1321'),
        ('point_of_sale', '0015_auto_20191110_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 11, 11), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='ordersubscribediscount',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Order'),
        ),
        migrations.AlterField(
            model_name='ordersubscribediscount',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.UserSubscribe'),
        ),
        migrations.CreateModel(
            name='OrderSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cart_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.CartSubscribe')),
                ('order_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_subscribe', to='point_of_sale.Order')),
                ('subscribe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.Subscribe')),
            ],
        ),
    ]
