# Generated by Django 2.2.6 on 2019-11-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0016_auto_20191111_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersubscribe',
            name='cart_related',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.CartSubscribe'),
        ),
    ]
