# Generated by Django 2.2.6 on 2019-11-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0018_auto_20191112_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='favorite_order',
            field=models.BooleanField(default=False),
        ),
    ]
