# Generated by Django 2.2 on 2019-11-17 07:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0026_auto_20191117_0946'),
        ('point_of_sale', '0019_order_favorite_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersubscribediscount',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='ordersubscribediscount',
            name='uses',
        ),
        migrations.AddField(
            model_name='ordersubscribediscount',
            name='subscribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribe.Subscribe'),
        ),
        migrations.AddField(
            model_name='ordersubscribediscount',
            name='total_uses',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 11, 17), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='ordersubscribe',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_subscribes', to='point_of_sale.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='ordersubscribe',
            unique_together={('order_related', 'subscribe')},
        ),
        migrations.RemoveField(
            model_name='ordersubscribe',
            name='cart_related',
        ),
        migrations.RemoveField(
            model_name='ordersubscribe',
            name='value',
        ),
    ]
