# Generated by Django 2.2.6 on 2019-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0020_auto_20191117_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersubscribe',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
