# Generated by Django 2.2.6 on 2019-11-19 14:05

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Κατασταση')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνια')),
                ('title', models.CharField(max_length=220, unique=True, verbose_name='Ονομασια')),
                ('image', models.ImageField(upload_to='blog/posts/main/', verbose_name='Εικονα')),
                ('text', tinymce.models.HTMLField(blank=True, verbose_name='Κειμενο')),
                ('slug', models.SlugField(allow_unicode=True, blank=True)),
                ('show_custom_date', models.BooleanField(default=False, verbose_name='Χρησιμοποιησε την ημερομηνια')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Κατασταση')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Τιτλος')),
                ('image', models.ImageField(upload_to='blog/categories/', verbose_name='Εικονα')),
                ('slug', models.SlugField(allow_unicode=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('post_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.PostCategory', verbose_name='Κατηγορια'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.upload_image)),
                ('post_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.Post')),
            ],
        ),
    ]
