# Generated by Django 2.2.6 on 2019-11-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='post_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_videos', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
