# Generated by Django 2.2.6 on 2020-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191122_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_first_page',
            field=models.BooleanField(default=False),
        ),
    ]
