# Generated by Django 2.2.6 on 2020-01-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_show_first_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='show_first_page',
            field=models.BooleanField(default=False, verbose_name='Εμφανιση Πρωτη Σελιδα'),
        ),
    ]
