# Generated by Django 2.2.6 on 2019-11-10 08:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.PostCategory', verbose_name='Κατηγορια'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνια'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blog/posts/main/', verbose_name='Εικονα'),
        ),
        migrations.AlterField(
            model_name='post',
            name='show_custom_date',
            field=models.BooleanField(default=False, verbose_name='Χρησιμοποιησε την ημερομηνια'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Κατασταση'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Κειμενο'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=220, unique=True, verbose_name='Ονομασια'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Κατασταση'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(upload_to='blog/categories/', verbose_name='Εικονα'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Τιτλος'),
        ),
    ]
