# Generated by Django 2.2 on 2020-01-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20191122_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetitle',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
