# Generated by Django 2.2 on 2019-10-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_product_different_color_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-active', '-id'], 'verbose_name_plural': '1. Products'},
        ),
    ]
