# Generated by Django 2.2 on 2019-10-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20191022_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='gift_message',
            field=models.CharField(max_length=200, unique=True, verbose_name='Μυνημα στον πελατη'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Κατασταση'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Τιτλος'),
        ),
    ]
