# Generated by Django 2.2.6 on 2019-10-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20191024_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeclass',
            name='is_needed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attributeclass',
            name='is_radio_button',
            field=models.BooleanField(default=True),
        ),
    ]
