# Generated by Django 2.2.6 on 2020-05-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_attributeclass_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeclass',
            name='products',
            field=models.ManyToManyField(related_name='my_attr_class', to='catalogue.Product'),
        ),
    ]
