# Generated by Django 2.2 on 2020-05-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20200517_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributetitle',
            options={'ordering': ['my_ordering'], 'verbose_name_plural': 'Τιμες Μεγεθολόγιου'},
        ),
        migrations.AddField(
            model_name='attributetitle',
            name='my_ordering',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='attributetitle',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attributetitle',
            name='level',
        ),
        migrations.RemoveField(
            model_name='attributetitle',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='attributetitle',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='attributetitle',
            name='tree_id',
        ),
    ]
