# Generated by Django 2.2.6 on 2019-11-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20191031_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_related', models.CharField(choices=[('HIDE', 'Hide')], max_length=20)),
                ('attribute_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_related', to='catalogue.AttributeClass')),
                ('attribute_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_selected', to='catalogue.AttributeClass')),
            ],
        ),
    ]
