# Generated by Django 2.2.4 on 2021-06-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20200518_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-active', '-featured_product', '-id'], 'verbose_name_plural': '1. Products'},
        ),
        migrations.AddField(
            model_name='productclass',
            name='cocktail',
            field=models.BooleanField(default=False),
        ),
    ]
