# Generated by Django 2.2.6 on 2019-11-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_attributerelated'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetitle',
            name='take_action',
            field=models.BooleanField(default=False),
        ),
    ]
