# Generated by Django 2.2.6 on 2020-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='choose_side',
            field=models.CharField(choices=[('p-left', 'Αριστερα'), ('p-right', 'Δεχιά'), ('none', 'Κάθόλου')], default='p-right', max_length=10, verbose_name='Επιλογη Πλευράς'),
        ),
        migrations.AddField(
            model_name='banner',
            name='color_letter',
            field=models.CharField(default='white', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.CharField(choices=[('a', 'Μεγάλο Banner --> (1920*1080)'), ('b', 'Μεσαίο Banner --> No Use. For future'), ('c', 'Μικρό Banner -->(600*250)')], default='a', max_length=1),
        ),
    ]
