# Generated by Django 2.2.4 on 2021-06-06 17:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20200116_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='choose_side',
            field=models.CharField(choices=[('p-left', 'Αριστερα'), ('p-right', 'Δεξιά'), ('none', 'Κάθόλου')], default='p-right', max_length=10, verbose_name='Επιλογη Πλευράς'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Σχόλια'),
        ),
    ]
