# Generated by Django 2.2 on 2020-01-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='extra_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
