# Generated by Django 2.2 on 2020-01-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_extra_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemattribute',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
