# Generated by Django 2.2 on 2019-10-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20191024_1356'),
        ('subscribe', '0003_auto_20191024_1356'),
        ('cart', '0003_auto_20190920_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cart_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('subscribe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.Subscribe')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemGifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.CartItem')),
                ('cart_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Product')),
            ],
        ),
    ]
