# Generated by Django 2.2 on 2020-05-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitemattribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemattribute',
            name='attribute',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.AttributeTitle'),
        ),
    ]
