# Generated by Django 2.2.6 on 2020-05-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200517_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartprofile',
            name='cellphone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Κινητό'),
        ),
        migrations.AlterField(
            model_name='cartprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Σταθερο Τηλεφωνο'),
        ),
    ]
