# Generated by Django 2.2.6 on 2019-10-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20191026_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSubscribeDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_uses', models.IntegerField(default=1)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cart_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
            ],
        ),
    ]
