# Generated by Django 2.2.6 on 2019-10-31 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_subscribe_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemgifts',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_gift', to='cart.CartItem'),
        ),
    ]
