# Generated by Django 2.2.6 on 2019-10-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20191031_0653'),
        ('cart', '0008_auto_20191031_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemattribute',
            name='attribute',
        ),
        migrations.AddField(
            model_name='cartitemattribute',
            name='attribute',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.Attribute'),
        ),
    ]
