# Generated by Django 2.2.6 on 2019-11-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20191031_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsubscribe',
            name='cart_related',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_subscribe', to='cart.Cart'),
        ),
    ]
