# Generated by Django 2.2.6 on 2019-11-10 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0018_auto_20191110_1055'),
        ('cart', '0010_auto_20191108_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsubscribediscount',
            name='subscribe_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.Subscribe'),
        ),
        migrations.AlterField(
            model_name='cartsubscribediscount',
            name='cart_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.AlterUniqueTogether(
            name='cartsubscribediscount',
            unique_together={('cart_related', 'subscribe_related')},
        ),
    ]
