# Generated by Django 2.2 on 2019-11-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0019_auto_20191110_1327'),
        ('cart', '0011_auto_20191110_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsubscribe',
            name='cart_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_subscribe', to='cart.Cart'),
        ),
        migrations.AlterUniqueTogether(
            name='cartsubscribe',
            unique_together={('cart_related', 'subscribe')},
        ),
    ]
