# Generated by Django 2.2 on 2019-11-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0020_auto_20191110_1518'),
        ('cart', '0012_auto_20191110_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsubscribediscount',
            name='cart_type',
            field=models.CharField(choices=[('a', 'Cart Subscribe'), ('b', 'User Subscribe')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='cartsubscribediscount',
            name='user_subscribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.UserSubscribe'),
        ),
        migrations.AlterField(
            model_name='cartsubscribediscount',
            name='subscribe_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.CartSubscribe'),
        ),
        migrations.AlterUniqueTogether(
            name='cartsubscribediscount',
            unique_together={('cart_related', 'subscribe_related', 'cart_type')},
        ),
    ]
