# Generated by Django 2.2.6 on 2019-11-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0024_auto_20191112_0816'),
        ('cart', '0013_auto_20191110_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsubscribediscount',
            name='subscribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribe.Subscribe'),
        ),
        migrations.AlterUniqueTogether(
            name='cartsubscribediscount',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cartsubscribediscount',
            name='subscribe_related',
        ),
        migrations.RemoveField(
            model_name='cartsubscribediscount',
            name='user_subscribe',
        ),
    ]
